server:
  port: 9000
spring:
  application:
    name: "card"
  datasource:
    url: jdbc:mysql://host.docker.internal:3306/cardsdb
    username: root
    password: root
  jpa:
    show-sql: true
  sql:
    init:
      mode: always
  config:
    import:
      - "optional:configserver:http://localhost:8071/"

management:
  endpoints:
    web:
      exposure:
        include:
          - "*"